### ISSUE TITLE
Make `--autoreload` a flag

### ISSUE THREAD

**Issue by ulope** [tortillagroup/django-rq-wrapper#3]
It would be much more convenient if `--autoreload` woud use the [`store_true` action](https://docs.python.org/3/library/argparse.html#action) to remove the need to pass `True`

**Comment by ulope** [comment]
Thanks for the fix. Unfortunately there is a small bug: When using the `store_true` action `type` isn't allowed anymore and needs to be removed.

**Comment by joesolly** [comment]
@ulope thanks for the catch. The update has been pushed in version 2.1
