### ISSUE TITLE
Django 2.2 Capability

### ISSUE THREAD

**Issue by CorneliusIV** [tortillagroup/django-rq-wrapper#4]
`django_rq_wrapper/management/commands/rqworkers.py`
`from django.utils.autoreload import reloader_thread`
gives and import error

We are currently getting an error with the latest version of Django. 
In Django 2.2 the autoreloader was rewritten so we need to figure out a function to hook into here
https://github.com/istrategylabs/django-rq-wrapper/blob/0e27133f63777461de7e9d2f9bfb8cb0c48afb1b/django_rq_wrapper/management/commands/rqworkers.py#L89

**Comment by joesolly** [comment]
> `django_rq_wrapper/management/commands/rqworkers.py`
> `from django.utils.autoreload import reloader_thread`
> gives and import error
> 
> We are currently getting an error with the latest version of Django.
> In Django 2.2 the autoreloader was rewritten so we need to figure out a function to hook into here
> https://github.com/istrategylabs/django-rq-wrapper/blob/0e27133f63777461de7e9d2f9bfb8cb0c48afb1b/django_rq_wrapper/management/commands/rqworkers.py#L89

Good luck :-P
